package cn.qy.MomoTech.NullEnchantment;

import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;

import java.lang.reflect.Field;

import static cn.qy.MomoTech.Items.Items.*;

public class Register {

    public static <T> void setStaticValue(Class<T> clazz, String field, Object value) {
        try {
            Field declaredField = clazz.getDeclaredField(field);
            declaredField.setAccessible(true);
            declaredField.set(null, value);
        } catch (IllegalAccessException | NoSuchFieldException var4) {
            var4.printStackTrace();
        }
    }

    public static void add(ItemStack[] it) {
        for (ItemStack it1 : it) {
            it1.addUnsafeEnchantment(Enchantment.DIG_SPEED, 1);
            it1.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        }
    }

    public static void run() {
        add(new ItemStack[]{MOMOTECH_QUANTUM_SINGULARITY, MOMOTECH_FROGLIGHT_GENERATOR, MOMOTECH_STONE_GENERATOR, MOMOTECH_ORE_GENERATOR, MOMOTECH_SAND_GENERATOR,
                MOMOTECH_COBBLESTONE_GENERATOR, MOMOTECH_GLASS_GENERATOR, MOMOTECH_TEMPLATE_GENERATOR, MOMOTECH_FISH_GENERATOR, MOMOTECH_DUST_GENERATOR,
                MOMOTECH_STONE_CHUNK_GENERATOR, MOMOTECH_ICE_GENERATOR, MOMOTECH_BASIC_GENERATOR, MOMOTECH_STRING_GENERATOR, MOMOTECH_COMMAND_BLOCK_GENERATOR, MOMOTECH_PURE_PRIMAL_MATTER,
                MOMOTECH_CARBON_GENERATOR, MOMOTECH_CHARACTER, MOMOTECH_ID_CARD, MOMOTECH_SUPREME_CORE, MOMOTECH_UNCONTROLLABLE_VOID,
                MOMOTECH_RANDOM_COPIER, MOMOTECH_FINAL_COPIER, MOMOTECH_COMPRESSED_MINERAL_QUARRY, MOMOTECH_NONE, MOMOTECH_BUG_FORMULA,
                MOMOTECH_BUG_DECIMAL, MOMOTECH_BUG_DATE, MOMOTECH_BUG_POSITIVE_OVERFLOW, MOMOTECH_BUG_NEGATIVE_OVERFLOW,
                MOMOTECH_BUG_SYSTEM, MOMOTECH_CALCULATOR, MOMOTECH_PRIMAL_MATTER_B, MOMOTECH_PRIMAL_MATTER_A,
                MOMOTECH_PRIMAL_MATTER_Y, MOMOTECH_PRIMAL_MATTER_CONSTRUCTOR, MOMOTECH_PURE_PRIMAL_MATTER, MOMOTECH_BUG_CRYSTAL, MOMOTECH_QUANTUM_CONSTRUCTOR,
                MOMOTECH_QYHB05, MOMOTECH_CHENMOSE, MOMOTECH_SKYBULE, MOMOTECH_PLUGIN, MOMOTECH_BUGGGGG, MOMOTECH_SATURATION_CHARM, MOMOTECH_WEIRD_THING, MOMOTECH_WEIRD_ARMOR, MOMOTECH_PRIMAL_MATTER_CONSTRUCTOR, MOMOTECH_UNCONTROLLABLE_VOID,
                MOMOTECH_NULL_GENERATOR, MOMOTECH_ADVANCED_NULL_GENERATOR, MOMOTECH_FINAL_CORE, MOMOTECH_BEE_GENERATOR, MOMOTECH_SPIDER_EYE_GENERATOR, MOMOTECH_UNCONTROLLABLE_VOID_GENERATOR,
                MOMOTECH_PRISMARINE_GENERATOR, MOMOTECH_PUMPKIN_CARVING_MACHINE, MOMOTECH_ITEM_CONSTRUCTOR, MOMOTECH_ID_WRITER, MOMOTECH_CHARACTER_CONSTRUCTOR,
                MOMOTECH_NULL, MOMOTECH_SYMBOL_DIVISION, MOMOTECH_SYMBOL_ADDITION, MOMOTECH_SYMBOL_MULTIPLICATION, MOMOTECH_SYMBOL_SUBTRACTION,
                MOMOTECH_INFINITY_GENERATOR, MOMOTECH_COMPRESSED_COBBLESTONE[49], MOMOTECH_NONE_CONSTRUCTOR, MOMOTECH_INTEGRATED_MACHINE_CORE, MOMOTECH_QUANTUM_BOX, MOMOTECH_QUANTUM, MOMOTECH_ENTANGLED_QUANTUM,
                MOMOTECH_ADVANCED_COBBLESTONE_GENERATOR, MOMOTECH_EQUIPMENT_REPAIRING_MACHINE, MOMOTECH_CHEST_GENERATOR, MOMOTECH_TELEPORTER,
                MOMOTECH_QUANTUM_BOX_OPENER, MOMOTECH_LIGHT_ESSENCE, MOMOTECH_DARK_ESSENCE, MOMOTECH_DIAMOND_PICKAXE_GENERATOR, MOMOTECH_MINERAL_SINGULARITY_DIAMOND,
                MOMOTECH_MINERAL_SINGULARITY_IRON, MOMOTECH_MINERAL_SINGULARITY_GOLD, MOMOTECH_MINERAL_SINGULARITY_QUARTZ, MOMOTECH_MINERAL_SINGULARITY_EMERALD, MOMOTECH_MINERAL_SINGULARITY_LAPIS, MOMOTECH_MINERAL_SINGULARITY_REDSTONE, MOMOTECH_METAL_SINGULARITY_COPPER, MOMOTECH_METAL_SINGULARITY_LEAD, MOMOTECH_METAL_SINGULARITY_MAGNESIUM, MOMOTECH_METAL_SINGULARITY_ZINC, MOMOTECH_METAL_SINGULARITY_TIN, MOMOTECH_METAL_SINGULARITY_SILVER,
                MOMOTECH_METAL_SINGULARITY_GOLD, MOMOTECH_METAL_SINGULARITY_ALUMINUM, MOMOTECH_IRON_CORE, MOMOTECH_INFINITY_INGOT, MOMOTECH_HIGHSPEED_GEO_MINER, MOMOTECH_MINERAL_SINGULARITY_COAL, MOMOTECH_INFINITY_COBBLESTONE_GENERATOR, MOMOTECH_MINERAL_SINGULARITY, MOMOTECH_METAL_SINGULARITY,
                MOMOTECH_FLINT_GENERATOR, MOMOTECH_INFINITY_SINGULARITY, MOMOTECH_ENTROPY_RECONSTRUCTOR, MOMOTECH_INFINITY_RESOURCE_CONDENSER, MOMOTECH_INFINITY_ENTROPY_RECONSTRUCTOR, MOMOTECH_INFINITY_MACHINE_CORE, MOMOTECH_LIGHT_AND_DARK_INGOT,
                MOMOTECH_INFINITY_DUST_EXTRACTOR, MOMOTECH_INFINITY_DUST_EXTRACTOR_ALUMINUM, MOMOTECH_INFINITY_DUST_EXTRACTOR_MAGNESIUM, MOMOTECH_INFINITY_DUST_EXTRACTOR_COPPER, MOMOTECH_INFINITY_DUST_EXTRACTOR_GOLD, MOMOTECH_INFINITY_DUST_EXTRACTOR_SILVER, MOMOTECH_INFINITY_DUST_EXTRACTOR_LEAD, MOMOTECH_INFINITY_DUST_EXTRACTOR_TIN, MOMOTECH_INFINITY_DUST_EXTRACTOR_ZINC, MOMOTECH_INFINITY_DUST_EXTRACTOR_IRON,
                MOMOTECH_INFINITY_URANIUM_EXTRACTOR, MOMOTECH_INFINITY_GEO_MINER, MOMOTECH_INFINITY_NUCLEAR_REACTOR, MOMOTECH_INFINITY_MINER, MOMOTECH_INFINITY_MINER_MINERAL_BLOCK,
                MOMOTECH_INFINITY_PLANT_GROWTH_CHAMBER, MOMOTECH_INFINITY_TREE_GROWTH_CHAMBER, MOMOTECH_STRING_GENERATOR, MOMOTECH_INFINITY_LIGHT_AND_DARK_COLLECTOR, MOMOTECH_CHARGED_QUANTUM, MOMOTECH_RANDOM_QUANTUM, MOMOTECH_RANDOM_QUANTUM_GENERATOR, MOMOTECH_CONCEPT, MOMOTECH_RESOURCE, MOMOTECH_CHARGED_INGOT,
                MOMOTECH_PRIMAL_COMMAND_BLOCK_IMPULSE, MOMOTECH_PRIMAL_COMMAND_BLOCK_REPEATING, MOMOTECH_PRIMAL_COMMAND_BLOCK_CHAIN, MOMOTECH_INFINITY_GEAR, MOMOTECH_ENDGAME_CAPACITOR, MOMOTECH_ENDGAME_GENERATOR, MOMOTECH_ENERGY_DEVOURER, MOMOTECH_ETERNAL_PARTICLE, MOMOTECH_ETERNAL_PARTICLE_CONSTUCTOR, MOMOTECH_ETERNAL_SINGULARITY
        });
    }
}
